# 认证令牌 (GROK3_AUTH_TOKEN)
token: "mio"

# 提示前的文本 (GROK3_BEFORE_PROMPT)
textBeforePrompt: ""

# 提示后的文本 (GROK3_AFTER_PROMPT)
textAfterPrompt: ""

# 保留聊天对话 (GROK3_KEEP_CHAT)
keepChat: false

# 忽略思考 (GROK3_IGNORE_THINKING)
ignoreThinking: false

# HTTP代理 (GROK3_HTTP_PROXY)
httpProxy: ""

# CF绕过代理 (CF_PROXY_URL)
cfProxyUrl: ""

# 管理页面可查阅用户组
viewerGroup:
  - ["viewer", "viewer"]

# 管理页面可管理用户组
adminGroup:
  - ["admin", "admin"]

