# 认证令牌 (GROK3_AUTH_TOKEN)
token: "abc123"

# HTTP代理 (GROK3_HTTP_PROXY)
httpProxy: ""

# CF绕过代理 (CF_PROXY_URL)
cfProxyUrl: ""

# 管理页面可查阅用户组
viewerGroup:
  - ["viewer", "viewer"]

# 管理页面可管理用户组
adminGroup:
  - ["admin", "admin"]

